### ISSUE TITLE
BRL pattern is missing the correct symbol

### ISSUE THREAD

**Issue by GuilhermeSa** [onepub-dev/money.dart#96]
Current implementation shows the default $ symbol for Brazilian Reals, the correct one would be R$. It used to be this way before moving to the YAML currencies. Tried looking at the history to see if this was something done on purpose, but I believe the correct configuration would be:

```YAML
- code: BRL
  decimalDigites: 2
  groupSeparator: "."
  decimalSeparator: ","
  symbol: "R$"
  country: "Brazil"
  unit: "Real"
  name: "Brazilian Real"
```
